<?php
/**
 * @category   Custom
 * @package    Custom_SubscriptionsOrders
 * @author     a@a.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Custom\SubscriptionsOrders\Setup;

use Magento\Framework\DB\Ddl\Table;
use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;

/**
 * @codeCoverageIgnore
 */
class InstallSchema implements InstallSchemaInterface
{
    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
        $installer = $setup;
        $installer->startSetup();

        /**
         * Creating table custom_subscriptionsorders
         */
        $table = $installer->getConnection()->newTable(
            $installer->getTable('custom_subscriptionsorders')
        )->addColumn(
            'subscriptionsorders_id',
            Table::TYPE_INTEGER,
            null,
            ['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
            'Entity Id'
        )->addColumn(
            'customer_id',
            Table::TYPE_INTEGER,
            null,
            ['unsigned' => true, 'nullable' => false],
            'customer_id'
        )->addColumn(
            'order_id',
            Table::TYPE_INTEGER,
            null,
            ['unsigned' => true, 'nullable' => false],
            'order_id'
        )->addColumn(
            'product_id',
            Table::TYPE_INTEGER,
            null,
            ['unsigned' => true, 'nullable' => false],
            'product_id'
        )->addColumn(
            'product_name',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'Product Name'
        )->addColumn(
            'price',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'price'
        )->addColumn(
            'price_discount',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'price'
        )->addColumn(
            'special_price',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'Special Price'
        )->addColumn(
            'special_price_discount',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'Special Price'
        )->addColumn(
            'discount',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'Discount'
        )->addColumn(
            'customer_name',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'Product Name'
        )->addColumn(
            'sku',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'sku'
        )->addColumn(
            'order_date',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'order_date'
        )->addColumn(
            'subscription_type',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'subscription_type'
        )->addColumn(
            'subscription',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'subscription'
        )->addColumn(
            'subscription_start',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'subscription_start'
        )->addColumn(
            'subscription_end',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'subscription_end'
        )->addColumn(
            'payment_method',
            Table::TYPE_TEXT,
            255,
            ['nullable' => true,'default' => null],
            'payment_method'
        )->addColumn(
            'status',
            Table::TYPE_INTEGER,
            1,
            ['nullable' => false,'default' => 0],
            'Status'
        )->addColumn(
            'created_at',
            Table::TYPE_TIMESTAMP,
            null,
            ['nullable' => false],
            'Created At'
        )->setComment(
            'Custom SubscriptionsOrders Table'
        );
        $installer->getConnection()->createTable($table);
        $installer->endSetup();
    }
}
