<?php
/**
 * @category   Custom
 * @package    Custom_SubscriptionFrequency
 * @author     thebhautik@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Custom\SubscriptionFrequency\Model\ResourceModel\SubscriptionFrequency;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'subscriptionfrequency_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Custom\SubscriptionFrequency\Model\SubscriptionFrequency',
            'Custom\SubscriptionFrequency\Model\ResourceModel\SubscriptionFrequency'
        );
    }
}